Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,89 +1,93 @@
+---
 version: 0.2
-
-phases: 
-    install:
-        runtime-versions:
-            python: 3.x
-        commands:
-            - echo Entered the install phase...
-            - gem install cfn-nag
-    pre_build:
-        commands:
-            - echo Entered the pre_build phase....
-            - echo Current directory is $CODEBUILD_SRC_DIR
-            - "export dirname=${PWD##*/}"
-            - echo Directory name $dirname
-            - echo Installing Taskcat using pip3...
-            - pip3 install cfn-lint taskcat
-            - echo Verifying Taskcat installation...
-            - taskcat -v
-            - echo "Configuring taskcat..."
-            - |
-              cat << EOF > ~/.taskcat.yml
-              general:
-                s3_regional_buckets: true
-              EOF
-            - echo Configuring aws cli...
-            - aws configure set default.region eu-west-1
-    build:
-        commands:
-            - echo Entered the build phase...
-            - echo run linting...
-            - cfn-lint templates/*
-            - cfn-lint templates/* > cfn_lint_output.log
-            - |
-              if $(grep -Fq "E" cfn_lint_output.log)
-              then
-                echo Linting FAILED!
-                exit 1
-              else
-                echo Linting Passed!
-                exit 0
-              fi
-            - echo run CFN-Nag to pinpoint security problems
-            - cfn_nag_scan --input-path  templates/*
-            - cfn_nag_scan --input-path  templates/* > cfn_nag_scan_output.log
-            - mkdir report || echo "dir report exists"
-            - SCAN_RESULT=$(cfn_nag_scan --fail-on-warnings --input-path  templates/* -o json > ./report/cfn_nag.out.json && echo OK || echo FAILED)
-            - echo Completed cfn scanning `date`
-            - echo Generating report and import to Security Hub `date`
-            - | 
-              source_repository=${!CODEBUILD_SRC_DIR##*/} jq  \
-              "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"CFN-NAG\", \
-              \"createdAt\": env.date, \"source_repository\": env.source_repository, \
-              \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
-              \"build_id\": env.CODEBUILD_BUILD_ID, \
-              \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
-              \"report\": . }" ./report/cfn_nag.out.json > payload.json
-            - if [[ "$FAIL_BUILD" = "true" && "$SCAN_RESULT" = "FAILED" ]]; then printf "\n\nFailiing pipeline as possible insecure configurations were detected\n\n" && exit 1; fi
-            - echo run Taskcat tests...
-            - taskcat test run --minimal-output --lint-disable
-            - |
-              if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
-              then
-                echo "Build failed!"
-                exit 1
-              else
-                echo "Build passed!"
-                exit 0
-              fi
-          finally:
-            - ls -1 taskcat_outputs
-            - ls -1 taskcat_outputs | while read LOG; do cat taskcat_outputs/$LOG; done
-            - >- # Do not remove
-              echo "Zipping and uploading report to S3 bucket: '$ARTIFACT_BUCKET'..."
-            - zip -r taskcat_report.zip taskcat_outputs
-            - aws s3 cp taskcat_report.zip s3://$ARTIFACT_BUCKET/taskcat_reports/$CODEBUILD_BUILD_ID.zip
-    post_build:
-        commands:
-            - echo Build completed on `date`
-reports: 
-    SecurityReports: 
-      files: 
-        - report/junit_scan_report.xml
-      discard-paths: 'yes'
-      file-format: JunitXml
+phases:
+  install:
+    runtime-versions:
+      python: 3.x
+    commands:
+      - echo Entered the install phase...
+      - gem install cfn-nag
+  pre_build:
+    commands:
+      - echo Entered the pre_build phase....
+      - echo Current directory is $CODEBUILD_SRC_DIR
+      - export dirname=${PWD##*/}
+      - echo Directory name $dirname
+      - echo Installing Taskcat using pip3...
+      - pip3 install cfn-lint taskcat
+      - echo Verifying Taskcat installation...
+      - taskcat -v
+      - echo "Configuring taskcat..."
+      - |
+        cat << EOF > ~/.taskcat.yml
+        general:
+          s3_regional_buckets: true
+        EOF
+      - echo Configuring aws cli...
+      - aws configure set default.region eu-west-1
+  build:
+    commands:
+      - echo Entered the build phase...
+      - echo run linting...
+      - cfn-lint templates/*
+      - cfn-lint templates/* > cfn_lint_output.log
+      - |
+        if $(grep -Fq "E" cfn_lint_output.log)
+        then
+          echo Linting FAILED!
+          exit 1
+        else
+          echo Linting Passed!
+          exit 0
+        fi
+      - echo run CFN-Nag to pinpoint security problems
+      - cfn_nag_scan --input-path  templates/*
+      - cfn_nag_scan --input-path  templates/* > cfn_nag_scan_output.log
+      - mkdir report || echo "dir report exists"
+      - SCAN_RESULT=$(cfn_nag_scan --fail-on-warnings --input-path  templates/*
+        -o json > ./report/cfn_nag.out.json && echo OK || echo FAILED)
+      - echo Completed cfn scanning `date`
+      - echo Generating report and import to Security Hub `date`
+      - |
+        source_repository=${!CODEBUILD_SRC_DIR##*/} jq  \
+        "{ \"messageType\": \"CodeScanReport\", \"reportType\": \"CFN-NAG\", \
+        \"createdAt\": env.date, \"source_repository\": env.source_repository, \
+        \"source_branch\": env.CODEBUILD_SOURCE_VERSION, \
+        \"build_id\": env.CODEBUILD_BUILD_ID, \
+        \"source_commitid\": env.CODEBUILD_RESOLVED_SOURCE_VERSION, \
+        \"report\": . }" ./report/cfn_nag.out.json > payload.json
+      - if [[ "$FAIL_BUILD" = "true" && "$SCAN_RESULT" = "FAILED" ]]; then
+        printf "\n\nFailiing pipeline as possible insecure configurations were
+        detected\n\n" && exit 1; fi
+      - echo run Taskcat tests...
+      - taskcat test run --minimal-output --lint-disable
+      - |
+        if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
+        then
+          echo "Build failed!"
+          exit 1
+        else
+          echo "Build passed!"
+          exit 0
+        fi
+    finally:
+      - ls -1 taskcat_outputs
+      - ls -1 taskcat_outputs | while read LOG; do cat taskcat_outputs/$LOG; done
+      - "echo \"Zipping and uploading report to S3 bucket:
+        '$ARTIFACT_BUCKET'...\""
+      - zip -r taskcat_report.zip taskcat_outputs
+      - aws s3 cp taskcat_report.zip
+        s3://$ARTIFACT_BUCKET/taskcat_reports/$CODEBUILD_BUILD_ID.zip
+  post_build:
+    commands:
+      - echo Build completed on `date`
+reports:
+  SecurityReports:
+    files:
+      - report/junit_scan_report.xml
+    discard-paths: yes
+    file-format: JunitXml
 artifacts:
   files:
     - taskcat_outputs/*
-  name: taskcat-report      
+  name: taskcat-report
